[server]
enableCORS = false
enableXsrfProtection = false
frameAncestors = ["*"]

[theme]
# Elegantna zlato-rjava za gumbe
primaryColor = "#c5a059"

# Nežna pastelno roza barva ozadja klepeta
backgroundColor = "#fff0f5"

# Malce temnejša roza za vnosno polje, da se loči
secondaryBackgroundColor = "#ffe4e1"

# Temno siva barva besedila za boljšo berljivost
textColor = "#31333F"

font = "sans serif"
